### ISSUE TITLE
Feature request: import signal backups from phone

### ISSUE THREAD

**Issue by danakianfar** [mattsta/signal-backup#2]
Since Signal Desktop does not sync retroactively, I can't use scab. I think it would be a great feature to add, or if there is a quick and dirty solution you could suggest!

**Comment by mattsta** [comment]
That would be a _great_ feature, but Signal actually goes to great lengths to deny users the ability to export databases from mobile devices. Signal [knows about the problem](https://github.com/signalapp/Signal-iOS/issues?q=is%3Aissue+backup) and they don't really seem to care.

Though, some android devices can export, but on iOS devices, Signal actually sets the "do not allow the database to ever be backed up" flag in their app, so it can never leave the device.

The _only_ way to sync Signal chats is to always have a Signal Desktop session paired to your mobile devices so it receives updates as well (since we can always see the Signal DB on desktops... for now).
